[pytest]
pythonpath = .
env_files =
    sendler/sendler.env
env =
    PRIVATE_KEY_PATH=api/private_key.pem
    PUBLIC_KEY_PATH=api/public_key.pem
    SENDLER_PASS=1111
    SENDLER_EMAIL=example@gmail.com
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function