"""1

Revision ID: 701495dfe6c2
Revises: 120a08a5116b
Create Date: 2026-09-01 17:19:14.099286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701495dfe6c2'
down_revision: Union[str, Sequence[str], None] = '120a08a5116b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('art', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('need_price', sa.Integer(), nullable=False),
    sa.Column('shop', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
