name: Backend CI

on:
  push:
    branches: [ "master", "develop" ] 
  pull_request:
    branches: [ "master" ]         

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen
      
      - name: Debug structure and run tests
        run: |
          echo "=== ТЕКУЩАЯ ДИРЕКТОРИЯ ==="
          pwd
          echo "=== СОДЕРЖИМОЕ КОРНЯ ==="
          ls -la
          echo "=== ГДЕ PYTHON ИЩЕТ МОДУЛИ ==="
          uv run python -c "import sys; print('\n'.join(sys.path))"
          echo "=== ЗАПУСК ТЕСТОВ ==="
          uv run python -m pytest


      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/api
        run: uv run pytest

